#!/usr/bin/env python3
"""ハブ index.html に「クローラが辿れる静的ゲーム一覧」を生成・埋め込む。

背景: ゲームカードは var GAMES 配列から JS で描画しているため、素のHTMLに
存在する <a> は十数本しかなく、検索エンジンが個別ゲームに到達できなかった。
このスクリプトは GAMES 配列をパースして、ジャンル別の静的リンク一覧を
ML_STATIC_INDEX マーカー間に書き込む。あわせて件数表記(NN本)を実数に揃える。

冪等。ゲーム追加後に毎回実行してよい（日次自動生成ジョブから呼ばれる）。
"""
from __future__ import annotations

import html
import re
import sys
from pathlib import Path

HUB = Path(__file__).resolve().parent.parent / "index.html"
START = "<!-- ML_STATIC_INDEX_START (generated by scripts/gen_static_index.py - do not edit by hand) -->"
END = "<!-- ML_STATIC_INDEX_END -->"


def parse_games(src: str) -> list[dict]:
    m = re.search(r"var GAMES = \[(.*?)\n    \];", src, re.S)
    if not m:
        sys.exit("GAMES 配列が見つからない")
    games = []
    for line in m.group(1).splitlines():
        line = line.strip()
        if not line.startswith("{"):
            continue
        rec = {}
        for key in ("title", "genre", "url", "desc_ja"):
            f = re.search(rf"{key}:\s*'((?:[^'\\]|\\.)*)'", line)
            if f:
                rec[key] = f.group(1).replace("\\'", "'")
        if rec.get("url") and rec.get("title"):
            games.append(rec)
    return games


def slug_of(url: str) -> str:
    return url.rstrip("/").split("/")[-1].replace(".vercel.app", "")


# genre 文字列はほぼ全件ユニーク（81種/84本）なので、粗いカテゴリに畳んで一覧を読める形にする
CATEGORIES: list[tuple[str, tuple[str, ...]]] = [
    ("パズル・ロジック", ("puzzle", "logic", "match", "sort", "nonogram", "sudoku", "jigsaw", "slide", "memory", "block", "merge", "word", "quiz", "minesweeper", "solitaire", "mahjong", "othello", "connect", "hangman", "search")),
    ("アクション・アーケード", ("action", "arcade", "runner", "jump", "flappy", "tap", "dodge", "clicker", "idle", "rhythm", "whack", "snake", "breakout", "platform", "escape")),
    ("シューティング・バトル", ("shoot", "fps", "shooter", "battle", "war", "defense", "invaders", "hunter", "archery", "slasher", "survivor")),
    ("スポーツ・3D", ("3d", "sport", "soccer", "bowling", "basketball", "darts", "hockey", "pinball", "fishing", "golf", "race", "pool", "sandbox")),
    ("育成・シミュレーション", ("sim", "gacha", "rpg", "tycoon", "manage", "farm", "craft", "build", "training", "care")),
    ("診断・カジュアル", ("fortune", "diagnos", "calendar", "omikuji", "typing", "casual", "card", "roulette", "test")),
]


def categorize(genre: str) -> str:
    g = (genre or "").lower()
    for name, keys in CATEGORIES:
        if any(k in g for k in keys):
            return name
    return "その他"


def build_block(games: list[dict]) -> str:
    by_genre: dict[str, list[dict]] = {}
    for g in games:
        by_genre.setdefault(categorize(g.get("genre", "")), []).append(g)

    out = [START]
    out.append('  <section class="all-games-index" style="max-width:1100px;margin:24px auto 8px;padding:0 16px;font-family:system-ui,sans-serif;">')
    out.append(f'    <h2 style="font-size:1.05rem;color:#ffd166;margin:0 0 4px;">🗂️ ゲーム全{len(games)}本 一覧 / All Games</h2>')
    out.append('    <p style="color:#9aa0a6;font-size:0.8rem;margin:0 0 12px;">ジャンル別インデックス。すべて無料・登録不要でブラウザからすぐ遊べます。</p>')
    order = [name for name, _ in CATEGORIES] + ["その他"]
    for genre in [c for c in order if c in by_genre]:
        out.append('    <div style="margin:0 0 10px;">')
        out.append(f'      <h3 style="font-size:0.85rem;color:#ff6b6b;margin:0 0 4px;font-weight:600;">{html.escape(genre)}</h3>')
        out.append('      <ul style="list-style:none;display:flex;flex-wrap:wrap;gap:6px;margin:0;padding:0;">')
        for g in sorted(by_genre[genre], key=lambda x: x["title"]):
            slug = slug_of(g["url"])
            href = f'{g["url"].rstrip("/")}/?utm_source=hub&utm_medium=all_index&utm_campaign={slug}'
            title = html.escape(g["title"])
            desc = html.escape(g.get("desc_ja", ""))[:80]
            out.append(
                f'        <li><a href="{href}" title="{desc}" '
                'style="display:inline-block;background:#15151c;border:1px solid #2c2c38;border-radius:8px;'
                'padding:5px 10px;color:#dfe1e5;text-decoration:none;font-size:0.8rem;">'
                f'{title}</a></li>'
            )
        out.append("      </ul>")
        out.append("    </div>")
    out.append("  </section>")
    out.append(END)
    return "\n".join(out)


def main() -> None:
    src = HUB.read_text(encoding="utf-8")
    games = parse_games(src)
    block = build_block(games)

    if START in src and END in src:
        src = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda _: block, src, flags=re.S)
    else:
        src = src.replace("  <!-- Footer -->", block + "\n\n  <!-- Footer -->", 1)

    # 件数表記を実数へ（"84本" 等の揺れを一掃）
    src = re.sub(r"\d+本の無料", f"{len(games)}本の無料", src)
    src = re.sub(r"ゲーム(\d+)本", f"ゲーム{len(games)}本", src)
    src = re.sub(r"(\d+)本の無料ブラウザゲーム", f"{len(games)}本の無料ブラウザゲーム", src)
    src = re.sub(r"遊ぶ(\d+)本の無料ゲームポータル", f"遊ぶ{len(games)}本の無料ゲームポータル", src)

    # canonical（無ければ head に追加）
    if 'rel="canonical"' not in src:
        src = src.replace(
            '  <link rel="stylesheet" href="style.css">',
            '  <link rel="canonical" href="https://musclelove-games.vercel.app/">\n  <link rel="stylesheet" href="style.css">',
            1,
        )

    HUB.write_text(src, encoding="utf-8")
    print(f"static index: {len(games)} games, {len({g.get('genre') for g in games})} genres -> {HUB}")


if __name__ == "__main__":
    main()
